name: Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'Frontend/lightwave-media-site/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    defaults:
      run:
        working-directory: ./Frontend/lightwave-media-site

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and type check
        run: |
          pnpm run lint
          pnpm run generate:types

      - name: Deploy preview to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: ./Frontend/lightwave-media-site
          wranglerVersion: '4.42.2'
          wranglerConfigPath: './wrangler.jsonc'

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://lightwave-media-site-${context.payload.pull_request.number}.jeschaeffer.workers.dev`;
            const adminUrl = `${previewUrl}/admin`;
            
            const comment = `## 🚀 Preview Deployment Ready!
            
            **Preview URL:** ${previewUrl}
            **Admin Panel:** ${adminUrl}
            
            This preview will be automatically updated when you push new commits to this PR.
            
            ---
            *Deployed by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
